# Site settings
title: Hardathon
description: "Первый железный хакатон в Ульяновске!"
email: hardathon@futurelab.space
url: https://hardathon.github.io

# Social networks usernames
social:
  - title: facebook
    url: http://fb.com/hardathon
  - title: vk
    url: http://vk.com/hardathon
